# Generated by Django 6.1 on 2026-08-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_badge_achievement_leaderboard_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='documentation_file',
            field=models.FileField(blank=True, null=True, upload_to='documentation/'),
        ),
        migrations.AddField(
            model_name='project',
            name='documentation_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('prototype', 'Prototype'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='prototype', max_length=12),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
