# Generated by Django 5.2.6 on 2026-08-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_initial_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
