# Generated by Django 5.2.6 on 2026-08-24 13:16

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='documentation_file',
            field=models.FileField(blank=True, null=True, upload_to='documentation/', validators=[core.validators.validate_document_upload]),
        ),
    ]
